name: Build and Deploy Fullstack App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout du code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Setup Node.js pour Angular
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3️⃣ Build Angular et copier dans backend
    - name: Build Angular
      run: |
        cd ngx-admin
        npm install --legacy-peer-deps
        npm run build --prod
        mkdir -p ../budget-backend-ahmed/src/main/resources/static
        cp -r dist/* ../budget-backend-ahmed/src/main/resources/static/

    # 4️⃣ Setup Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    # 5️⃣ Cache Maven
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # 6️⃣ Build Spring Boot
    - name: Build Spring Boot
      run: mvn clean package -DskipTests
      working-directory: budget-backend-ahmed

    # 7️⃣ Vérifier le JAR généré
    - name: Check JAR file
      run: ls -lh budget-backend-ahmed/target

    # 8️⃣ Login Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 9️⃣ Déployer le JAR sur Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: budget-backend-ahmed
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: budget-backend-ahmed/target/*.jar

    # 🔟 Configurer les variables d’environnement dans Azure
    - name: Configure App Settings (Environment Variables)
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az webapp config appsettings set --resource-group budget-rg --name budget-backend-ahmed --settings \
            SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }} \
            SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
            SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            FILE_UPLOAD_DIR=${{ secrets.FILE_UPLOAD_DIR }} \
            JWT_SECRET=${{ secrets.JWT_SECRET }} \
            JWT_EXPIRATION_MS=${{ secrets.JWT_EXPIRATION_MS }} \
            SPRING_JPA_DATABASE_PLATFORM=${{ secrets.SPRING_JPA_DATABASE_PLATFORM }} \
            SPRING_JPA_HIBERNATE_DDL_AUTO=${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }} \
            JAVA_VERSION=${{ secrets.JAVA_VERSION }}
