name: Build & Deploy Backend + Frontend to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BACKEND_DIR: budget-backend-ahmed
      FRONTEND_DIR: ngx-admin 

    steps:
      # 1) Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Setup Java 17
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3) Cache Maven dependencies
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4) Build Backend
      - name: Build Backend with Maven
        run: |
          cd $BACKEND_DIR
          mvn -B clean package -DskipTests
          cd -

      # 5) Build Frontend Angular
      - name: Build Angular Frontend
        run: |
          cd $FRONTEND_DIR
          npm install --legacy-peer-deps
          ng build --configuration production
          cd -

      # 6) Copy frontend build to backend static folder
      - name: Copy Frontend to Backend Static
        run: |
          rm -rf $BACKEND_DIR/src/main/resources/static
          mkdir -p $BACKEND_DIR/src/main/resources/static
          cp -r $FRONTEND_DIR/dist/* $BACKEND_DIR/src/main/resources/static/

      # 7) Package backend jar into zip for Azure
      - name: Package Backend ZIP
        run: |
          cd $BACKEND_DIR/target
          rm -f app.zip
          zip app.zip *.jar
          ls -l app.zip
          cd -

      # 8) Configure Azure App Settings
      - name: Configure App Settings
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az webapp config appsettings set \
              --resource-group budget-rg \
              --name budget-backend-ahmed \
              --settings \
              SPRING_PROFILES_ACTIVE=prod \
              SPRING_DATASOURCE_URL="${{ secrets.DB_URL }}" \
              SPRING_DATASOURCE_USERNAME="${{ secrets.DB_USER }}" \
              SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              FILE_UPLOAD_DIR=/home/site/wwwroot/uploads/images \
              JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              JWT_EXPIRATION_MS=86400000

      # 9) Deploy ZIP to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: budget-backend-ahmed
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.BACKEND_DIR }}/target/app.zip
