name: Build & Deploy Fullstack to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout du code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Setup Node.js (Angular)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3️⃣ Build Angular
    - name: Build Angular
      run: |
        cd ngx-admin
        npm install
        npm run build -- --configuration production
        # Copier le build Angular dans le dossier static du backend
        cp -r dist/ngx-admin/* ../budget-backend-ahmed/src/main/resources/static/

    # 4️⃣ Setup Java 17
    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    # 5️⃣ Cache Maven
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # 6️⃣ Build Spring Boot
    - name: Build Spring Boot
      run: mvn clean package -DskipTests
      working-directory: budget-backend-ahmed

    # 7️⃣ Vérifier le JAR généré
    - name: List JAR
      run: ls -lh budget-backend-ahmed/target

    # 8️⃣ Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: budget-backend-ahmed
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: budget-backend-ahmed/target/*.jar

    # 9️⃣ Configurer les variables d'environnement
    - name: Configure App Settings
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az webapp config appsettings set \
            --resource-group budget-rg \
            --name budget-backend-ahmed \
            --settings \
              SPRING_PROFILES_ACTIVE=prod \
              SPRING_DATASOURCE_URL="${{ secrets.DB_URL }}" \
              SPRING_DATASOURCE_USERNAME="${{ secrets.DB_USER }}" \
              SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              FILE_UPLOAD_DIR=/home/site/wwwroot/uploads/images \
              JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              JWT_EXPIRATION_MS=86400000
