name: Build & Deploy Spring Boot to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Setup Java 17
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3) Cache Maven dependencies
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4) Build Maven project (skip tests)
      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      # 5) Préparer un ZIP pour Azure
      - name: Package ZIP
        run: |
          cd target
          rm -f app.zip
          zip app.zip *.jar
          ls -l app.zip
          cd -

      # 6) Déployer sur Azure Web App avec publish profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: budget-backend-ahmed
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/app.zip
